workspace:
  base: /drone
  path: src/github.com/owncloud-docker/enterprise

branches:
  - daily-master

clone:
  git:
    image: plugins/git:1
    pull: true

pipeline:
  tarball:
    image: plugins/download:1
    pull: true
    secrets: [ download_username, download_password ]
    source: https://download.owncloud.com/internal/owncloud-daily-enterprise-complete-master.tar.bz2

  wait:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 600 docker:2375

  build:
    image: toolhippie/docker:latest
    pull: true
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t registry.owncloud.com/owncloud/enterprise:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} .

  server:
    image: toolhippie/docker:latest
    pull: true
    detach: true
    secrets: [ owncloud_license_key ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker run -p 8000:80 -e OWNCLOUD_LICENSE_KEY registry.owncloud.com/owncloud/enterprise:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}

  test:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 600 docker:8000
      - curl -sSf http://docker:8000/status.php

  prepublish:
    image: toolhippie/docker:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin registry.owncloud.com
      - docker push registry.owncloud.com/owncloud/enterprise:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}
    when:
      event: [ push, pull_request ]

  clair:
    image: toolhippie/klar:latest
    pull: true
    secrets:
      - source: docker_username
        target: docker_user
      - source: docker_password
        target: docker_password
    environment:
      - CLAIR_ADDR=clair.owncloud.com
      - CLAIR_OUTPUT=High
    commands:
      - klar registry.owncloud.com/owncloud/enterprise:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}
    when:
      event: [ push, pull_request ]

  publish:
    image: toolhippie/docker:latest
    pull: true
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin registry.owncloud.com
      - docker tag registry.owncloud.com/owncloud/enterprise:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER} registry.owncloud.com/owncloud/enterprise:daily-master
      - docker push registry.owncloud.com/owncloud/enterprise:daily-master
    when:
      event: [ push ]

  # FIXME: currently it removes the built image as well.
  # cleanup:
  #   image: toolhippie/reg:latest
  #   pull: true
  #   secrets: [ docker_username, docker_password ]
  #   commands:
  #     - reg rm --username $DOCKER_USERNAME --password $DOCKER_PASSWORD registry.owncloud.com/owncloud/enterprise:${DRONE_COMMIT_SHA}-${DRONE_BUILD_NUMBER}
  #   when:
  #     event: [ push, pull_request ]
  #     status: [ success, failure ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_urls ]
    when:
      local: false
      event: [ push ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: docker
    when:
      local: false
      event: [ push ]
      status: [ changed, failure ]

services:
  docker:
    image: docker:18.04-dind
